### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by dianaicd** [sneuensc/mapache#10]
under development:

- [x] add bamdamage rule
- [x] sex assignment: define thresholds to set it as "undetermined"; possibility to merge chromosomes with different names
- [x] rename variables in sex assignation
- [x] re-plot bamdamage data and send to report
- [x] add table with depth by chromosome
- [x] merge tables per genome into single table
- [x] add figures for the final tables
- [ ] PreSeq
- [x] add multiqc on everything (samtools flagstat + fastqc + Preseq + qualimap)
- [x] add qualimap (histogram of mapping qualities)

**Comment by sneuensc** [comment]
Done
