### ISSUE TITLE
Problem while trying to run the Dry Run

### ISSUE THREAD

**Issue by mudymudy** [sneuensc/mapache#33]
Hi, thank you for developing this pipeline. 
I'm trying to run the Dry Run but I get this error every time:

TypeError in line 751 of /home/bromero/genotyping/mapache/workflow/scripts/utils.py:
stat: path should be string, bytes, os.PathLike or integer, not dict
  File "/home/bromero/genotyping/mapache/workflow/Snakefile", line 74, in <module>
  File "/home/bromero/genotyping/mapache/workflow/scripts/utils.py", line 751, in set_chromosome_names
  File "/home/bromero/anaconda3/envs/mapache/lib/python3.9/genericpath.py", line 30, in isfile
TypeError in line 751 of /home/bromero/genotyping/mapache/workflow/scripts/utils.py:
stat: path should be string, bytes, os.PathLike or integer, not dict
  File "/home/bromero/genotyping/mapache/workflow/Snakefile", line 74, in <module>
  File "/home/bromero/genotyping/mapache/workflow/scripts/utils.py", line 751, in set_chromosome_names
  File "/home/bromero/anaconda3/envs/mapache/lib/python3.9/genericpath.py", line 30, in isfile

If I go to the ./workflow/Snakemake file, the line 74 says:

                                                                                               
## get all chromosome names and store them in the dict config[chromosomes][genome][all] for later use
for genome in GENOMES:
    set_chromosome_names(genome)

Which is maybe related to the error message:  
""stat: path should be string, bytes, os.PathLike or integer, not dict""

I honestly have no idea but any help would be appreciated since I'm very interested in running this! 

Thank you in advance,

Bruno

**Comment by sneuensc** [comment]
Dear mudymudy,

Thank you for your interest in mapache. 

Thank you for reporting the issue. To reproduce it, I need some more information: 

- Which version of mapache did you use (commit/realease)? 
- Are you trying to run the test configuration file?
- How did you specify the reference genome?

**Comment by sneuensc** [comment]
Dear Bruno
The current version of mapache requires a local reference genome. The path to the reference genome has to be set in the config file under  'genome'. Please have a look at https://github.com/sneuensc/mapache/tree/master/config. The different index files of the reference genome(s) are build automatically if not present. The path in your message to the reference genome is the one from the default config file and is the path to our reference genome.
All the best

**Comment by sneuensc** [comment]
I assume that the problem is solved and close the ticket.
